# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20170210_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
