# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20170221_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='inbox.Message'),
        ),
    ]
