# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170123_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='profile_pic',
        ),
    ]
