# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170213_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(related_name='followed_by', to='users.UserProfile'),
        ),
    ]
