# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170213_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='users.UserProfile'),
        ),
    ]
