# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170206_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.TextField(null=True),
        ),
    ]
