# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20170211_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
